---
#
# Playbook to check OSP install for common performance tuning issues
#

- hosts: controller
  remote_user: heat-admin
  vars:
    tuned_profile: throughput-performance
    rabbitmq_fd: 16384
    mariadb_max_connections: 4096
  roles:
  - common
  - controller
  - keystone

- hosts: compute
  remote_user: heat-admin
  vars:
    tuned_profile: virtual-host
  roles:
  - common
  - compute

- hosts: ceph
  remote_user: heat-admin
  vars:
    tuned_profile: throughput-performance
  roles:
  - common
  - ceph

- hosts : compute
  name : Report from Computes
  vars:
    reserved_host_memory_check: 2048
  tasks :
    - name : Report Compute(s) reserved_host_memory
      fail:
        msg: "Compute node reserved memory too low"
      when: hostvars[item].reserved_host_memory|int < reserved_host_memory_check
      with_items: groups['compute']
