---
- name: Dump all vars
  template: src=dump_facts.j2 dest={{ browbeat_path }}/metadata/machine_facts.json

- name: Generate metadata jsons
  shell : python {{ browbeat_path }}/browbeat/metadata.py {{ browbeat_path }}/metadata
